# 练习1：NumPy array数组与其形状

In [ ]:
import numpy as np

# 创建名为 daily_minutes 的 NumPy 数组
daily_minutes = np.array([30, 45, 60, 20, 50, 40, 35])
print(f'本周每天学习时长：{daily_minutes} 分钟')

# 假设每天额外增加 15 分钟，计算新的学习时长
increased_minutes = daily_minutes + 15
print(f'每天额外增加 15 分钟后的学习时长：{increased_minutes} 分钟')

# 将增加后的学习时长转换为小时
daily_hours = increased_minutes / 60
print(f'每天学习时长（小时）：{daily_hours} 小时')

# 一维数组的 shape
print(f'一维数组的形状：{daily_minutes.shape}')

# 二维数组的 shape
weekly_minutes = np.array(
    [[30, 45, 60, 20, 50, 40, 35],
     [25, 30, 55, 15, 45, 35, 30],
     [35, 40, 65, 25, 55, 45, 40]]
)
print(f'二维数组的形状：{weekly_minutes.shape}')

本周每天学习时长：[30 45 60 20 50 40 35] 分钟
每天额外增加 15 分钟后的学习时长：[45 60 75 35 65 55 50] 分钟
每天学习时长（小时）：[0.75       1.         1.25       0.58333333 1.08333333 0.91666667
 0.83333333] 小时
一维数组的形状：(7,)
二维数组的形状：(3, 7)


# 练习2：NumPy 数组索引

In [ ]:
import numpy as np

daily_minutes = np.array([30, 45, 60, 20, 50, 40, 35])

# 负数索引
# 数据：      [60, 75, 90, 45]
# 正数索引：    0   1   2   3
# 负数索引：   -4  -3  -2  -1

# 获取索引为 0 的元素，也就是星期一学习时长
first_day_minutes = daily_minutes[0]
print(f'星期一的学习时长：{first_day_minutes} 分钟')

# 获取索引为 2 的元素，也就是星期三学习时长
third_day_minutes = daily_minutes[2]
print(f'星期三的学习时长：{third_day_minutes} 分钟')

# 获取最后一个元素，也就是星期天学习时长
last_day_minutes = daily_minutes[-1]
print(f'星期天的学习时长：{last_day_minutes} 分钟')

# 获取倒数第三个元素，也就是星期五学习时长
third_last_day_minutes = daily_minutes[-3]
print(f'星期五的学习时长：{third_last_day_minutes} 分钟')

print('=' * 100)

# 二维数组索引--数组名[行索引, 列索引]
# 行索引 第0列 第1列 第2列 第3列
#   0	  60	75	 90	   45
#   1	  80	60	 120   90
#   2	  45	75	 60	   105

Weekly_minutes = np.array(
    [[60, 75, 90, 45, 63],
     [80, 60, 120, 90, 32],
     [45, 75, 60, 105, 34]]
)

# 获取第 1 周第 3 天的学习时长
print(f'第 1 周第 3 天的学习时长：{Weekly_minutes[0, 2]} 分钟')

# 获取第 2 周第 4 天的学习时长
print(f'第 2 周第 4 天的学习时长：{Weekly_minutes[1, 3]} 分钟')

# 获取第 3 周的全部数据
print(f'第 3 周的全部数据：{Weekly_minutes[2]} 分钟')

# 使用负数索引获取最后一周的全部数据
print(f'最后一周的全部数据：{Weekly_minutes[-1]} 分钟')

星期一的学习时长：30 分钟
星期三的学习时长：60 分钟
星期天的学习时长：35 分钟
星期五的学习时长：50 分钟
第 1 周第 3 天的学习时长：90 分钟
第 2 周第 4 天的学习时长：90 分钟
第 3 周的全部数据：[ 45  75  60 105  34] 分钟
最后一周的全部数据：[ 45  75  60 105  34] 分钟


# 练习3：NumPy 数组切片

In [ ]:
# 一维数组切片--数组名[开始索引:结束索引]
import numpy as np

daily_minutes = np.array([60, 75, 90, 45, 80])

# 获取索引 1 到索引 3 之前的数据
# 包含索引 1，但不包含索引 3
selected_minutes = daily_minutes[1:3]
print(f'索引 1 到索引 3 之前的数据：{selected_minutes} 分钟')

# 省略开始位置，从数组开头取到索引 3 之前
first_third_minutes = daily_minutes[:3]
print(f'从数组开头取到索引 3 之前的数据：{first_third_minutes} 分钟')

# 省略结束位置，从索引 2 开始取到数组末尾
last_minutes = daily_minutes[2:]
print(f'从索引 2 开始取到数组末尾的数据：{last_minutes} 分钟')

# 获取整个数组
print(f'整个数组的数据 ：{daily_minutes[:]} 分钟')

print('=' * 100)

# 二维数组切片--数组名[行切片, 列切片]
weekly_minutes = np.array(
    [[60, 75, 90, 45, 63],
     [80, 60, 120, 90, 32],
     [45, 75, 60, 105, 34]]
)

# 获取第 1 周的前 3 天数据
print(f'第一周的前三天数据：{weekly_minutes[0:1, 0:3]} 分钟')

# 获取第 2 周从第 2 天到第 4 天的数据
print(f'第二周的第 2 到第 4 天数据：{weekly_minutes[1:2, 1:4]} 分钟')

# 获取前两周的全部数据
print(f'获取前两周的全部数据：\n{weekly_minutes[0:2, :]} 分钟')

# 获取所有周的第 3 天数据
print(f'所有周第三天的数据：\n{weekly_minutes[:, :3]} 分钟')

# 获取后两周的后两天数据
print(f'后两周的后两天数据：\n{weekly_minutes[1:, 3:]} 分钟')

索引 1 到索引 3 之前的数据：[75 90] 分钟
从数组开头取到索引 3 之前的数据：[60 75 90] 分钟
从索引 2 开始取到数组末尾的数据：[90 45 80] 分钟
整个数组的数据 ：[60 75 90 45 80] 分钟
第一周的前三天数据：[[60 75 90]] 分钟
第二周的第 2 到第 4 天数据：[[ 60 120  90]] 分钟
获取前两周的全部数据：
[[ 60  75  90  45  63]
 [ 80  60 120  90  32]] 分钟
所有周第三天的数据：
[[ 60  75  90]
 [ 80  60 120]
 [ 45  75  60]] 分钟
后两周的后两天数据：
[[ 90  32]
 [105  34]] 分钟


# 练习4：使用字典创建 DataFrame

In [ ]:
import pandas as pd

# 创建一个字典
# 字典中的每个键会成为 DataFrame 的一列
students_data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [20, 22, 21],
    "Grade": [85.5, 90, 78]
}

# 使用字典创建 DataFrame
study_df = pd.DataFrame(students_data)
print(f"学生数据：\n{study_df}")

# 使用 .columns 查看列名
print(f"列名：{study_df.columns}")

# DataFrame 的索引
print(f"索引：{study_df.index}")

# 查看 DataFrame 的形状
print(f"形状：{study_df.shape}")

# 查看数据类型
print(f'数据类型：\n{study_df.dtypes}')

学生数据：
      Name  Age  Grade
0    Alice   20   85.5
1      Bob   22   90.0
2  Charlie   21   78.0
列名：Index(['Name', 'Age', 'Grade'], dtype='str')
索引：RangeIndex(start=0, stop=3, step=1)
形状：(3, 3)
数据类型：
Name         str
Age        int64
Grade    float64
dtype: object


# 练习5：使用 read_csv 读取 CSV 和 Excel 文件

In [6]:
import pandas as pd

# 导入 os 模块，用于查看当前工作目录
import os
# 输出 Notebook 当前使用的工作目录
print(os.getcwd())

# 指定 CSV 文件的位置
# 当前 Notebook 位于 notebooks 文件夹中
# .. 表示返回上一级目录
csv_path = 'D:/Ai_Learning/python basic/data/raw/study_log.csv'

# 使用 read_csv 读取 CSV 文件
# 读取结果会成为一个 DataFrame
csv_df = pd.read_csv(csv_path)
print(f"从 CSV 文件读取的学生数据：\n{csv_df}")

# 使用 .head() 查看前几行数据，默认显示前 5 行
print(f"前 5 行数据：\n{csv_df.head()}")
# 查看 DataFrame 的前 3 行
print(f"前 3 行数据：\n{csv_df.head(3)}")

print('=' * 100)

excel_path = 'D:/Ai_Learning/python basic/data/raw/study_log.xlsx'

# 使用 read_excel 读取 Excel 文件
# 读取结果会被保存为一个 DataFrame
excel_df = pd.read_excel(excel_path)
print(f"从 Excel 文件读取的学生数据：\n{excel_df}")

# 创建一个 ExcelFile 对象，用于查看工作簿信息
excel_file = pd.ExcelFile(excel_path)
# 输出 Excel 文件中的所有工作表名称
print("工作表名称：", excel_file.sheet_names)

# 判断 CSV 和 Excel 读取后的数据是否完全一致
is_same = csv_df.equals(excel_df)
print("两份数据是否完全一致：", is_same)

d:\Ai_Learning\python basic
从 CSV 文件读取的学生数据：
          date  week  module  duration_minutes  completed         note
0   2026-07-27     1  Python              60.0       True      变量与数据类型
1   2026-07-28     1  Python              75.0       True        列表和字典
2   2026-07-29     1  Python              90.0       True         循环练习
3   2026-07-30     1  Python              45.0       True         条件判断
4   2026-07-31     1  Python              80.0       True         函数练习
5   2026-08-01     2   NumPy              60.0       True         数组基础
6   2026-08-02     2   NumPy              75.0       True      shape练习
7   2026-08-02     2   NumPy              75.0       True      shape练习
8   2026-08-03     2  Pandas               NaN      False  DataFrame练习
9   2026-08-04     2  Pandas             -30.0       True        CSV读取
10  2026-08-05     2  Pandas             900.0       True         数据清洗
前 5 行数据：
         date  week  module  duration_minutes  completed     note
0  2026-07-27     1  Python 

# 练习6：使用 dropna() 处理空值

In [13]:
import pandas as pd

csv_path = 'D:/Ai_Learning/python basic/data/raw/study_log.csv'

csv_df = pd.read_csv(csv_path, encoding='utf-8-sig')
print(f"从 CSV 文件读取的学生数据：\n{csv_df}")

# 使用 .isna() 检查空值
# 空值会显示为 True，非空值显示为 False
missing_values = csv_df.isna()
print(f"缺失值检查结果：\n{missing_values}")

# 统计每一列包含多少个空值
missing_count = csv_df.isna().sum()
print(f"每一列的缺失值数量：\n{missing_count}")

# 使用 dropna() 删除包含空值的行
cleaned_df = csv_df.dropna()
print(f"删除空值后的数据：\n{cleaned_df}")

# 输出清洗前的数据形状
print("清洗前形状：", study_df.shape)
# 输出清洗后的数据形状
print("清洗后形状：", cleaned_df.shape)

# 只检查 duration_minutes 列
# 如果学习时长为空，就删除对应记录
clean_df2 = csv_df.dropna(subset=['duration_minutes'])
print(f"删除 duration_minutes 列中空值后的数据：\n{clean_df2}")

# 找出 duration_minutes 为空的记录
missing_data = csv_df[csv_df['duration_minutes'].isna()]
print(f"学习时长为空的记录：\n{missing_data}")

从 CSV 文件读取的学生数据：
          date  week  module  duration_minutes  completed         note
0   2026-07-27     1  Python              60.0       True      变量与数据类型
1   2026-07-28     1  Python              75.0       True        列表和字典
2   2026-07-29     1  Python              90.0       True         循环练习
3   2026-07-30     1  Python              45.0       True         条件判断
4   2026-07-31     1  Python              80.0       True         函数练习
5   2026-08-01     2   NumPy              60.0       True         数组基础
6   2026-08-02     2   NumPy              75.0       True      shape练习
7   2026-08-02     2   NumPy              75.0       True      shape练习
8   2026-08-03     2  Pandas               NaN      False  DataFrame练习
9   2026-08-04     2  Pandas             -30.0       True        CSV读取
10  2026-08-05     2  Pandas             900.0       True         数据清洗
缺失值检查结果：
     date   week  module  duration_minutes  completed   note
0   False  False   False             False      False  False


# 练习7：使用 drop_duplicates() 删除重复数据

In [16]:
import pandas as pd

csv_path = 'D:/Ai_Learning/python basic/data/raw/study_log.csv'

csv_df = pd.read_csv(csv_path, encoding='utf-8-sig')

clean_df = csv_df.dropna()

duplicate_flags = clean_df.duplicated()
print(f"重复记录检查结果：\n{duplicate_flags}")

duplicate_count = clean_df.duplicated().sum()
print(f"重复记录总数：\n{duplicate_count}")

# 找出后出现的重复记录
duplicate_records = clean_df[clean_df.duplicated()]
print(f"重复记录：\n{duplicate_records}")

# 找出所有参与重复的记录
# keep=False 表示不保留任何一个作为非重复项
all_records = clean_df[clean_df.duplicated(keep=False)]
print(f"所有参与重复的记录：\n{all_records}")

# 删除完全重复的行
no_duplicate = clean_df.drop_duplicates()
print(f"删除重复记录后的数据：\n{no_duplicate}")

# 根据指定字段判断记录是否重复
no_duplicates = clean_df.drop_duplicates(subset=['date', 'week', 'module', 'duration_minutes'])
print(f"根据日期，周次，模块和学习时长删除重复记录后的数据：\n{no_duplicates}")

# keep 决定重复数据中保留哪一条
# 保留第一条
first_keep = clean_df.drop_duplicates(keep='first')
print(f"保留重复数据中的第一条记录后的数据：\n{first_keep}")
# 保留最后一条
last_keep = clean_df.drop_duplicates(keep='last')
print(f"保留重复数据中的最后一条记录后的数据：\n{last_keep}")

# 删除空值和重复记录后，索引会不连续，可以使用 reset_index() 重新生成连续索引
new_index = no_duplicate.reset_index(drop=True)
print(f"删除空值和重复记录后，重新生成连续索引的数据：\n{new_index}")

重复记录检查结果：
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
9     False
10    False
dtype: bool
重复记录总数：
1
重复记录：
         date  week module  duration_minutes  completed     note
7  2026-08-02     2  NumPy              75.0       True  shape练习
所有参与重复的记录：
         date  week module  duration_minutes  completed     note
6  2026-08-02     2  NumPy              75.0       True  shape练习
7  2026-08-02     2  NumPy              75.0       True  shape练习
删除重复记录后的数据：
          date  week  module  duration_minutes  completed     note
0   2026-07-27     1  Python              60.0       True  变量与数据类型
1   2026-07-28     1  Python              75.0       True    列表和字典
2   2026-07-29     1  Python              90.0       True     循环练习
3   2026-07-30     1  Python              45.0       True     条件判断
4   2026-07-31     1  Python              80.0       True     函数练习
5   2026-08-01     2   NumPy              60.0       True     数组基础
6   2026-08-02     2   Nu

# 练习8：使用条件筛选清洗异常数据

In [32]:
import pandas as pd

csv_path = 'D:/Ai_Learning/python basic/data/raw/study_log.csv'

csv_df = pd.read_csv(csv_path, encoding='utf-8-sig')

clean_df = csv_df.dropna().drop_duplicates().reset_index(drop='True')
print(f"删除空值和重复记录后的数据：\n{clean_df}")

# 判断每一条学习时长是否大于 0和小于 480 分钟
valid_df = (
    (clean_df['duration_minutes'] > 0) & 
     (clean_df['duration_minutes'] <= 480)
)
print(f"学习时长大于 0 和小于 480 分钟的记录：\n{valid_df}")

# 只保留学习时长大于 0 和小于 480 分钟的记录
positive_df= clean_df[valid_df]
print(f"只保留学习时长大于 0 和小于 480 分钟的记录后的数据：\n{positive_df}")

# 在前面加 ~，表示将判断结果取反
# 找出不符合有效时长规则的记录
invalid_df = clean_df[~valid_df]
print(f"不符合有效时长规则的记录：\n{invalid_df}")

new_index = positive_df.reset_index(drop='True')
print(f"删除无效学习时长记录后，重新生成连续索引的数据：\n{new_index}")

删除空值和重复记录后的数据：
         date  week  module  duration_minutes  completed     note
0  2026-07-27     1  Python              60.0       True  变量与数据类型
1  2026-07-28     1  Python              75.0       True    列表和字典
2  2026-07-29     1  Python              90.0       True     循环练习
3  2026-07-30     1  Python              45.0       True     条件判断
4  2026-07-31     1  Python              80.0       True     函数练习
5  2026-08-01     2   NumPy              60.0       True     数组基础
6  2026-08-02     2   NumPy              75.0       True  shape练习
7  2026-08-04     2  Pandas             -30.0       True    CSV读取
8  2026-08-05     2  Pandas             900.0       True     数据清洗
学习时长大于 0 和小于 480 分钟的记录：
0     True
1     True
2     True
3     True
4     True
5     True
6     True
7    False
8    False
Name: duration_minutes, dtype: bool
只保留学习时长大于 0 和小于 480 分钟的记录后的数据：
         date  week  module  duration_minutes  completed     note
0  2026-07-27     1  Python              60.0       True  变量与数据类型
1  

# 练习9：使用 groupby() 按周统计学习时长

In [15]:
import pandas as pd

csv_path = 'D:/Ai_Learning/python basic/data/raw/study_log.csv'

csv_df = pd.read_csv(csv_path, encoding='utf-8-sig')

clean_df = csv_df. dropna().drop_duplicates().reset_index(drop='True')
print(f"删除空值和重复记录后的数据：\n{clean_df}")

# groupby() 用于按照某一列中的类别，把数据分成若干组
# 基本写法：DataFrame.groupby("分组列")["统计列"].sum()
weekly_total = clean_df.groupby('week')['duration_minutes'].sum()
print(f"每周学习时长总和：\n{weekly_total}")

# 为了让统计结果更像普通表格，可以重置索引
weekly_index = clean_df.groupby('week')['duration_minutes'].sum().reset_index()
print(f"每周学习时长总和（重置索引后）：\n{weekly_index}")

# 修改统计列名称，当前列名仍然是：duration_minutes。为了表达得更准确，可以将其改为：total_minutes
weekly_column = clean_df.groupby('week')['duration_minutes'].sum().reset_index().rename(columns={'duration_minutes': 'total minutes'})
print(f"每周学习时长统计：\n{weekly_column}")

# 同时计算总时长和平均时长，groupby() 还可以配合 .agg() 进行多项统计
# sum：每周总学习时长，mean：每条记录的平均学习时长
weekly_df = clean_df.groupby('week')['duration_minutes'].agg(['sum', 'mean']).reset_index()
print(f'同时计算总学习时长和平均时长：\n{weekly_df}')

删除空值和重复记录后的数据：
         date  week  module  duration_minutes  completed     note
0  2026-07-27     1  Python              60.0       True  变量与数据类型
1  2026-07-28     1  Python              75.0       True    列表和字典
2  2026-07-29     1  Python              90.0       True     循环练习
3  2026-07-30     1  Python              45.0       True     条件判断
4  2026-07-31     1  Python              80.0       True     函数练习
5  2026-08-01     2   NumPy              60.0       True     数组基础
6  2026-08-02     2   NumPy              75.0       True  shape练习
7  2026-08-04     2  Pandas             -30.0       True    CSV读取
8  2026-08-05     2  Pandas             900.0       True     数据清洗
每周学习时长总和：
week
1     350.0
2    1005.0
Name: duration_minutes, dtype: float64
每周学习时长总和（重置索引后）：
   week  duration_minutes
0     1             350.0
1     2            1005.0
每周学习时长统计：
   week  total minutes
0     1          350.0
1     2         1005.0
同时计算总学习时长和平均时长：
   week     sum    mean
0     1   350.0   70.00
1     2  

# 练习10：使用 value_counts() 统计类别出现次数

In [5]:
import pandas as pd

csv_path = 'D:/Ai_Learning/python basic/data/raw/study_log.csv'

csv_df = pd.read_csv(csv_path, encoding='utf-8-sig')

clean_df = csv_df.dropna().drop_duplicates().reset_index(drop=True)
print(f'删除空值和重复记录后的数据：\n{clean_df}')

# 本节统计 module 列中每个学习模块出现了多少次
# 基本写法：DataFrame["列名"].value_counts()
module_count = clean_df['module'].value_counts(ascending=False) # ascending=False 表示按照次数从高到低排列，True相反
print(f'各模块学习记录次数：\n{module_count}')

# 将统计结果转换为 DataFrame，并且修改统计列名称
module_df = clean_df['module'].value_counts(ascending=True).reset_index().rename(columns={'count': 'record_count'})
print(f'各模块学习记录次数：\n{module_df}')

# 统计各模块所占比例
# normalize=True 表示返回比例，而不是记录数量
module_proportions = clean_df['module'].value_counts(normalize=True) * 100
print(f"各模块记录占比：{module_proportions}")

删除空值和重复记录后的数据：
         date  week  module  duration_minutes  completed     note
0  2026-07-27     1  Python              60.0       True  变量与数据类型
1  2026-07-28     1  Python              75.0       True    列表和字典
2  2026-07-29     1  Python              90.0       True     循环练习
3  2026-07-30     1  Python              45.0       True     条件判断
4  2026-07-31     1  Python              80.0       True     函数练习
5  2026-08-01     2   NumPy              60.0       True     数组基础
6  2026-08-02     2   NumPy              75.0       True  shape练习
7  2026-08-04     2  Pandas             -30.0       True    CSV读取
8  2026-08-05     2  Pandas             900.0       True     数据清洗
各模块学习记录次数：
module
Python    5
NumPy     2
Pandas    2
Name: count, dtype: int64
各模块学习记录次数：
   module  record_count
0   NumPy             2
1  Pandas             2
2  Python             5
各模块记录占比：module
Python    55.555556
NumPy     22.222222
Pandas    22.222222
Name: proportion, dtype: float64


# 练习11：使用 sort_values() 对数据排序

In [24]:
import pandas as pd

csv_path = 'D:/Ai_Learning/python basic/data/raw/study_log.csv'

csv_df = pd.read_csv(csv_path, encoding='utf-8-sig')

clean_df = csv_df.dropna().drop_duplicates().reset_index(drop=True)
print(f'删除空值和重复记录后的数据：\n{clean_df}')

# sort_values() 的基本写法
# DataFrame.sort_values(by="列名", ascending=True)，by：根据哪一列排序，ascending=True：从小到大排列，ascending=False：从大到小排列
# 按照 duration_minutes 从小到大排列：
duration_ascending = clean_df.sort_values(by='duration_minutes', ascending=True).reset_index(drop=True)
print(f'按学习时长升序排列：\n{duration_ascending}')

# 按模块统计并排序投入时间，使用已经学过的 groupby() 统计各模块总时长
module_summary = clean_df.groupby('module')['duration_minutes'].sum().reset_index().rename(columns={'duration_minutes': 'total_minutes'})
print(f'各模块总学习时长：\n{module_summary}')

module_ascending = module_summary.sort_values(by='total_minutes', ascending=True)
print(f'各模块投入时间排名：\n{module_ascending}')

# 将各模块总分钟数转换为小时
module_ascending['total_hours'] = module_ascending['total_minutes'] / 60
module_ascending['total_hours'] = module_ascending['total_hours'].round(2)
print(f'各模块学习时长排名(小时)：\n{module_ascending}')

# 同时根据多个列排序，先按 week 升序排列，同一周内再按学习时长降序排列：
sort_df = clean_df.sort_values(by=['week', 'duration_minutes'], ascending=[True, False]).reset_index(drop=True)
print(f'按周数和学习时长排序：\n{sort_df}')

删除空值和重复记录后的数据：
         date  week  module  duration_minutes  completed     note
0  2026-07-27     1  Python              60.0       True  变量与数据类型
1  2026-07-28     1  Python              75.0       True    列表和字典
2  2026-07-29     1  Python              90.0       True     循环练习
3  2026-07-30     1  Python              45.0       True     条件判断
4  2026-07-31     1  Python              80.0       True     函数练习
5  2026-08-01     2   NumPy              60.0       True     数组基础
6  2026-08-02     2   NumPy              75.0       True  shape练习
7  2026-08-04     2  Pandas             -30.0       True    CSV读取
8  2026-08-05     2  Pandas             900.0       True     数据清洗
按学习时长升序排列：
         date  week  module  duration_minutes  completed     note
0  2026-08-04     2  Pandas             -30.0       True    CSV读取
1  2026-07-30     1  Python              45.0       True     条件判断
2  2026-08-01     2   NumPy              60.0       True     数组基础
3  2026-07-27     1  Python              60.0     

# 练习12：使用 to_excel() 导出清洗后的数据

In [29]:
import pandas as pd

csv_path = 'D:/Ai_Learning/python basic/data/raw/study_log.csv'

csv_df = pd.read_csv(csv_path, encoding='utf-8-sig')

clean_df = csv_df.dropna().drop_duplicates().reset_index(drop=True)
print(f'删除空值和重复记录后的数据：\n{clean_df}')

output_path = "D:/Ai_Learning/python basic/data/processed/cleaned_study_log.xlsx"

clean_df.to_excel(output_path, index=False, sheet_name='clean_data') # index=False导出时会删除索引

print("清洗后的 Excel 文件已成功导出。")

# 重新读取刚刚生成的 Excel 文件
check_df = pd.read_excel(output_path, sheet_name='clean_data')
print(f'重新读取的数据：\n{check_df}')

删除空值和重复记录后的数据：
         date  week  module  duration_minutes  completed     note
0  2026-07-27     1  Python              60.0       True  变量与数据类型
1  2026-07-28     1  Python              75.0       True    列表和字典
2  2026-07-29     1  Python              90.0       True     循环练习
3  2026-07-30     1  Python              45.0       True     条件判断
4  2026-07-31     1  Python              80.0       True     函数练习
5  2026-08-01     2   NumPy              60.0       True     数组基础
6  2026-08-02     2   NumPy              75.0       True  shape练习
7  2026-08-04     2  Pandas             -30.0       True    CSV读取
8  2026-08-05     2  Pandas             900.0       True     数据清洗
清洗后的 Excel 文件已成功导出。
重新读取的数据：
         date  week  module  duration_minutes  completed     note
0  2026-07-27     1  Python                60       True  变量与数据类型
1  2026-07-28     1  Python                75       True    列表和字典
2  2026-07-29     1  Python                90       True     循环练习
3  2026-07-30     1  Python     

# 第二周综合题：学习记录数据清洗与统计系统

In [ ]:
print(f'====================第一部分：NumPy 基础综合====================')

import numpy as np

study_array = np.array([
    [60, 75, 90, 45, 80],
    [90, 60, 120, 75, 105],
    [45, 80, 60, 90, 120]]
)

# 使用 shape 输出数组形状
print(f'学习数组形状：{study_array.shape}')

# 单个索引，获取第 2 周第 3 天的数据
print(f'第 2 周第 3 天学习时间：{study_array[1, 2]}')

# 整行索引，获取第 3 周全部数据
print(f'第 3 周学习时间：{study_array[2]}')

# 一维切片，获取第 1 周前 3 天的数据
print(f'第 1 周前 3 天学习时间：\n{study_array[0:1, 0:3]}')

# 二维切片，获取后两周的后 3 天数据
print(f'后两周的后 3 天学习时间：\n{study_array[1:3, 2:5]}')

# 整列提取，获取所有周第 2 天的数据
print(f'所有周第 2 天学习时间：\n{study_array[0:3, 1:2]}')

# 将全部分钟数转换成小时
study_hours = study_array / 60
print(f'全部分钟数转换成小时：\n{study_hours}')

print(f'====================第二部分：读取原始学习数据====================')

import pandas as pd

csv_path= 'D:/Ai_Learning/python basic/data/raw/study_log.csv'

study_df = pd.read_csv(csv_path, encoding='utf-8-sig')

# 输出前 5 行数据
print(f'前 5 行数据：\n{study_df.head()}')

# 输出DataFrame 的 shape
print(f'数据的形状：{study_df.shape}')

# 输出所有列名
print(f'所有列名：{study_df.columns}')

# 输出各列的数据类型
print(f'各列的数据类型：{study_df.dtypes}')

# 输出各列空值数量
print(f'各列空值数量：{study_df.isna().sum()}')

# 输出重复记录数量
print(f'重复记录数量：{study_df.duplicated().sum()}')

print(f'====================第三部分：数据清洗====================')

# 输出空值
missing_data = study_df[study_df['duration_minutes'].isna()]
print(f'输出空值：\n{missing_data}')

# 输出重复数据
duplicate_data = study_df[study_df.duplicated(keep=False)]
print(f'输出重复数据：\n{duplicate_data}')

# 删除空值和重复数据
clean_df = study_df.dropna().drop_duplicates()

# 寻找异常学习时长 
valid_data = (clean_df['duration_minutes'] > 0) & (clean_df['duration_minutes'] <= 480)
print(f'寻找异常时长记录：\n{valid_data}')

# 删除异常学习时长
valid_df = clean_df[valid_data].reset_index(drop=True)
print(f'删除异常学习时长：\n{valid_df}')

print(f'====================第四部分：按周统计学习时间，按模块统计投入时间并排序====================')

# 按周统计学习时间
weekly_total = valid_df.groupby('week')['duration_minutes'].sum().reset_index().rename(columns={'duration_minutes': 'total_minutes'})
weekly_total['total_hours'] = weekly_total['total_minutes'] / 60
weekly_total['total_hours'] = weekly_total['total_hours'].round(2)
print(f'按周统计学习时间：\n{weekly_total}')

# 按模块统计投入时间并排序
module_time = valid_df.groupby('module')['duration_minutes'].sum().reset_index().rename(columns={'duration_minutes': 'total_minutes'})
module_ascending =module_time.sort_values(by='total_minutes', ascending=True) 
module_ascending['total_hours'] = module_ascending['total_minutes'] / 60
module_ascending['total_hours'] = module_ascending['total_hours'].round(2)
print(f'按模块统计投入时间并排序：\n{module_ascending }')

# 各模块学习记录次数
module_count = valid_df['module'].value_counts(ascending=True).reset_index().rename(columns={'count': 'record_count'})
print(f'各模块学习记录次数：\n{module_count}')

print(f'====================第五部分：导出最终 Excel====================')



====================第一部分：NumPy 基础综合====================
学习数组形状：(3, 5)
第 2 周第 3 天学习时间：120
第 3 周学习时间：[ 45  80  60  90 120]
第 1 周前 3 天学习时间：
[[60 75 90]]
后两周的后 3 天学习时间：
[[120  75 105]
 [ 60  90 120]]
所有周第 2 天学习时间：
[[75]
 [60]
 [80]]
全部分钟数转换成小时：
[[1.         1.25       1.5        0.75       1.33333333]
 [1.5        1.         2.         1.25       1.75      ]
 [0.75       1.33333333 1.         1.5        2.        ]]
====================第二部分：读取原始学习数据====================
前 5 行数据：
         date  week  module  duration_minutes  completed     note
0  2026-07-27     1  Python              60.0       True  变量与数据类型
1  2026-07-28     1  Python              75.0       True    列表和字典
2  2026-07-29     1  Python              90.0       True     循环练习
3  2026-07-30     1  Python              45.0       True     条件判断
4  2026-07-31     1  Python              80.0       True     函数练习
数据的形状：(11, 6)
所有列名：Index(['date', 'week', 'module', 'duration_minutes', 'completed', 'note'], dtype='str')
各列的数据类型：date      